Failure # 1 (occurred at 2023-11-21_10-56-39)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=46015, ip=10.10.10.121, actor_id=c8511067854911567385caf501000000, repr=PPO)
  File "/home/jonas/Dissertation/mini-project/.venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in __init__
    self._env_id, self.env_creator = self._get_env_id_and_creator(
  File "/home/jonas/Dissertation/mini-project/.venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2294, in _get_env_id_and_creator
    return env_specifier, _global_registry.get(ENV_CREATOR, env_specifier)
  File "/home/jonas/Dissertation/mini-project/.venv/lib/python3.10/site-packages/ray/tune/registry.py", line 270, in get
    return pickle.loads(value)
AttributeError: Can't get attribute 'Highway.observation_space' on <module '__main__' from '/home/jonas/Dissertation/mini-project/.venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py'>
